# Copy to config/nginx/sites-enabled/10-app.conf and edit.
server {
    listen 8080;
    server_name app.example.net;

    include /etc/nginx/snippets/security-headers.conf;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        include /etc/nginx/snippets/rate-limit-general.conf;

        proxy_pass http://192.168.10.20:8080;
    }
}
