# Copy to config/nginx/sites-enabled/20-websocket.conf and edit.
server {
    listen 8080;
    server_name ws.example.net;

    location / {
        include /etc/nginx/snippets/proxy-common.conf;
        include /etc/nginx/snippets/websocket.conf;
        include /etc/nginx/snippets/rate-limit-general.conf;

        proxy_pass http://192.168.10.30:3000;
    }
}
